### ISSUE TITLE
Filter sounds off

### ISSUE THREAD

**Issue by johansmolinski** [cnvogelg/captvolt-vcv#1]
Trying to make a simple patch with a filter sweep based on an external LFO, but I fail getting it smooth. It sounds like each value change of the filter cutoff does something weird with the audio, resulting in a "jittery" sweep. Is this a known issue? Do you need more details? I attach a screenshot of my patch.

![image](https://user-images.githubusercontent.com/45559525/107422988-175a9200-6b1c-11eb-8476-80788fae3c13.png)

**Comment by cnvogelg** [comment]
The SID chip is a digitally controlled analog synthesizer. Therefore the control values are discrete (here the cutoff is 11 bit wide) and also the update interval of the values is limited by the frequency the CPU could write to these registers. In fact most  music players on the C64 only updated the sound registers in intervals based on the screen refresh rate (PAL 50 Hz or NTSC 60 Hz). By default this module simulates this behavior: all input voltages (here 0-10V) are mapped to discrete values (here 0-2047) and the update rate of the registers is also limited to 50 Hz. You can change the update rate with the context menu with "VSync Oversample" and the "CPU Clock". "No VSync" completely disables the update limitation and updates the values immediately at audio rate. Another alternative is to use the "Clk" input and provide your own update rate...

**Comment by johansmolinski** [comment]
Thanks for the explanation and suggested “workaround”. I’ll play around with it. I don’t really understand the correlation between the sync rate and the jittery sound. If I was to provide my own sync, what would be a good strategy to avoid the jitter? As high rate as possible or timed to match some properties of the audio? Well, I guess I’ll learn as I play around with it.

**Comment by johansmolinski** [comment]
Just a quick follow up question. You say the cutoff is 11 bit. By looking at the code, filter_regs.cpp, you have this function:

```
void FilterRegs::setCutOff(uint16_t freq)
{
    freq &= CUTOFF_MAX;
    uint8_t old_lo = regs[CUTOFF_LO];
    uint8_t old_hi = regs[CUTOFF_HI];
    regs[CUTOFF_LO] = (uint8_t)(freq & 0xff);
    regs[CUTOFF_HI] = (uint8_t)(freq >> 8);
    if(regs[CUTOFF_LO] != old_lo) {
        dirty |= (1<<CUTOFF_LO);
    }
    if(regs[CUTOFF_HI] != old_hi) {
        dirty |= (1<<CUTOFF_HI);
    }
}
```

In the lines where you set the `regs[CUTOFF_LO]` and `regs[CUTOFF_HI]`, you type convert the `freq` to `uint_8`. Is this correct? Aren't we wasting three bits from the cutoff resolution by doing this?

Edit: Ah, never mind. `CUTOFF_LO` and `CUTOFF_HI` correspond to the low and high byte of the register. Looking good then. Damn, I really though you could make a smooth sweep without hearing the discrete steps. Anyway... :)

By the way. By not waiting for vsync, the "weird" jitter is gone, but the cutoff steps are even more audible.

**Comment by cnvogelg** [comment]
I think I found the root cause: samples were not read correctly from the SID engine :( fixed in  63e023b2.

**Comment by johansmolinski** [comment]
Thanks for looking in to this! Actually, I think the result is even worse now. The steps sounds even larger now, though unfortunately I've changed the patch a bit so I can't A-B test.

**Comment by cnvogelg** [comment]
Finally found the bug: filter values were not correctly converted for the registers: LO reg only keeps 3 bits the others are in HI... see 8bdef7b

**Comment by johansmolinski** [comment]
Oh, that was a tricky one! Looking forward to test tomorrow.

**Comment by johansmolinski** [comment]
There we go! Thanks for sorting this out! Now this module behaves just like I remember the SID chip. So good!

**Comment by johansmolinski** [comment]
Please don't forget to upload 1.0.1 to vcvrack.com, as it drastically change the experience with this module. :)

**Comment by cnvogelg** [comment]
Sure, I already submitted the new release: https://github.com/VCVRack/library/issues/674
